### ISSUE TITLE
Working with eslint?

### ISSUE THREAD

**Issue by brettz9** [benjaminRomano/linter-manager#5] opened 2015-10-24 20:48 UTC
Hi,

Using your plug-in with linter-eslint, I can see an error type, the path, and the line, but nothing shows for the description though I'd expect to see the rule ID and rule description (as with the default linter UI), ideally as two separate sortable columns. Does support need to be added on your end or on the provider's end?

**Comment by benjaminRomano** [comment] 2015-10-25 14:04
The description is missing due to the linter-eslint package. I'll talk with them and see if they can fix it.

As for having a column for ruleId, I can't do that because each package has their own way of displaying it or don't have it at all

**Comment by brettz9** [comment] 2015-10-25 17:31
Ok, thanks, I see the issue at AtomLinter/linter-eslint/issues/239 . Ok, so there is no way to provide an array (say as your own custom property) that you can read to make separate columns?

**Comment by benjaminRomano** [comment] 2015-10-25 21:06
The linter packages for specific languages could add additional properties that I could use, but I'd rather conform to the conventions set by the atom-community/linter package.

I made a pull request to the linter-eslint package.  https://github.com/benjaminRomano/linter-eslint/commit/6f9d5be43e9350df4897ba2c776acebc1fde1a8d 

Once its merged into master, the description should start to show up in linter-manager.

**Comment by brettz9** [comment] 2015-10-25 21:13
Great, thanks! I do think it is a pity though that you have that power in your program which isn't being fully leveraged as far as the array idea. I think it would serve a great need to be able to group all eslint message types together (as well as by line and error/warning). Anyways, thanks for your initiative on sending over the PR!

**Comment by benjaminRomano** [comment] 2015-10-25 21:26
I added a new column, linter, in the table. I guess this is an expected field even though the linter's documentation doesn't mention it.

Also by the way, in the table you can sort by multiple columns by shift clicking table headers. This will let you group messages by linter, error/warning and line number.

**Comment by brettz9** [comment] 2015-10-25 22:06
That's a very nice feature with multiple column sorting--and I hadn't considered that it doesn't really matter for sorting if the error ID and error message are joined together with eslint since they will always be co-associated.

And that's cool about the linter column being added.

Thanks much! Hope your PR will be accepted soon.

**Comment by benjaminRomano** [comment] 2015-10-28 19:42
Looks like my PR was reverted...

The problem is that linter messages can either display text or provide HTML but not both at the same time, and this is problematic for me because my custom view's can't display the HTML properly.

I created an issue at https://github.com/atom-community/linter/issues/976 to hopefully update the linter API so that it's possible to provide a text alternative for the HTML.

**Comment by benjaminRomano** [comment] 2015-10-28 21:57
I update linter-manager to support html, which works for the eslint-linter package.

**Closed as completed by benjaminRomano** 2015-10-28 21:57 UTC

**Comment by brettz9** [comment] 2015-10-29 04:32
Great, thanks so much! Looks good...

**Comment by brettz9** [comment] 2015-11-19 19:04
FYI, I've filed AtomLinter/linter-eslint/issues/236 which, if addressed, looks like it should work with linter-manager since you say you are using HTML now.
